# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conducteur_horaire_ligne_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_conducteur',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_horaire',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_ligne',
        ),
        migrations.DeleteModel(
            name='Conducteur',
        ),
        migrations.DeleteModel(
            name='Horaire',
        ),
        migrations.DeleteModel(
            name='Ligne',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
