# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conducteur_horaire_ligne_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_conducteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Conducteur'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_horaire',
            field=models.ManyToManyField(blank=True, null=True, to='api.Horaire'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ligne'),
        ),
    ]
